version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes: 
      - ./data:/data/db
    ports:
      - $MONGO_PORT:$MONGO_PORT
    networks:
      - server_net

  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:18
    container_name: node
    restart: always
    volumes:
      - ./app:/home/node/app
      - ./app/node_modules:/home/node/app/node_modules
    working_dir: /home/node/app
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    env_file: .env
    environment:
      MONGODB_URL: mongodb://root:example@mongo:27017/
      MONGO_USERNAME: $MONGO_USERNAME
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_HOSTNAME: mongo
      MONGO_PORT: $MONGO_PORT
      MONGO_DB: $MONGO_DB 
    networks:
      - server_net
    command: bash -c "npm install && npm run start"

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on: 
      - node
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - server_net

volumes:
  app: {}
  node_modules: {}
  data: {}
networks:
  server_net:
    driver: bridge